document.addEventListener('DOMContentLoaded',function(){checkAdminLogin();});
function checkAdminLogin(){const m=document.getElementById('adminLoginModal'),d=document.getElementById('adminDashboard');document.getElementById('adminLoginForm').addEventListener('submit',function(e){e.preventDefault();const u=document.getElementById('adminUser').value,p=document.getElementById('adminPass').value;if(u==='BANTIBOSS00'&&p==='BANTI200772003'){localStorage.setItem('adminLoggedIn','true');m.classList.remove('active');d.classList.remove('hidden');loadDashboard();}else alert('❌ Wrong Credentials!');});if(localStorage.getItem('adminLoggedIn')==='true'){m.classList.remove('active');d.classList.remove('hidden');loadDashboard();}}
document.getElementById('logoutBtn').addEventListener('click',function(){localStorage.removeItem('adminLoggedIn');location.reload();});
document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',function(){const t=this.dataset.tab;document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));this.classList.add('active');document.getElementById(t+'Tab').classList.add('active');}));
function loadDashboard(){updateStats();loadWorkersTab();loadJobsTab();}
function updateStats(){const a=JSON.parse(localStorage.getItem('applications')||'[]'),w=a.filter(a=>a.type==='worker').length,j=a.filter(a=>a.type==='job').length,p=a.filter(a=>a.status==='paid').length,r=p*50;document.getElementById('totalWorkers').textContent=w;document.getElementById('totalJobs').textContent=j;document.getElementById('totalRevenue').textContent=`₹${r}`;document.getElementById('pendingApps').textContent=p;document.getElementById('pendingWorkersCount').textContent=`(${a.filter(a=>a.type==='worker'&&a.status==='pending').length})`;document.getElementById('pendingJobsCount').textContent=`(${a.filter(a=>a.type==='job'&&a.status==='pending').length})`;}
function loadWorkersTab(){const a=JSON.parse(localStorage.getItem('applications')||'[]'),p=a.filter(a=>a.type==='worker'&&a.status==='pending'),ap=a.filter(a=>a.type==='worker'&&a.status==='approved');document.getElementById('pendingWorkersList').innerHTML='';p.forEach((w,i)=>document.getElementById('pendingWorkersList').appendChild(createWorkerItem(w,i)));document.getElementById('approvedWorkersList').innerHTML='';ap.forEach((w,i)=>document.getElementById('approvedWorkersList').appendChild(createWorkerItem(w,i,true)));}
function loadJobsTab(){const a=JSON.parse(localStorage.getItem('applications')||'[]'),p=a.filter(a=>a.type==='job'&&a.status==='pending'),ap=a.filter(a=>a.type==='job'&&a.status==='approved');document.getElementById('pendingJobsList').innerHTML='';p.forEach((j,i)=>document.getElementById('pendingJobsList').appendChild(createJobItem(j,i)));document.getElementById('approvedJobsList').innerHTML='';ap.forEach((j,i)=>document.getElementById('approvedJobsList').appendChild(createJobItem(j,i,true)));}
function createWorkerItem(w,i,ap=false){const d=document.createElement('div');d.className='worker-item';d.innerHTML=`<h4>${w.name}</h4><p><strong>💳 Payment:</strong> ${w.paymentId||'Pending'}</p><p><strong>🆔 Aadhar:</strong> ${w.aadhar}</p><p><strong>📱 Phone:</strong> ${w.phone}</p><p><strong>📍 Location:</strong> ${w.location}</p><p><strong>⭐ Skills:</strong> ${w.skills}</p><div class="action-btns">${ap?'<button class="btn btn-danger btn-sm" onclick="deleteApp('+i+',\''+w.type+'\')"><i class="fas fa-trash"></i> Delete</button>':'<button class="btn btn-success btn-sm" onclick="approveApp('+i+',\''+w.type+'\')"><i class="fas fa-check"></i> Approve</button><button class="btn btn-danger btn-sm" onclick="deleteApp('+i+',\''+w.type+'\')"><i class="fas fa-trash"></i> Delete</button>'}</div>`;return d;}
function createJobItem(j,i,ap=false){const d=document.createElement('div');d.className='job-item';d.innerHTML=`<h4>${j.shopName}</h4><p><strong>💳 Payment:</strong> ${j.paymentId||'Pending'}</p><p><strong>👤 Owner:</strong> ${j.ownerName}</p><p><strong>💼 Job:</strong> ${j.jobType}</p><p><strong>💰 Salary:</strong> ₹${j.salary}</p><p><strong>📱 Phone:</strong> ${j.phone}</p><div class="action-btns">${ap?'<button class="btn btn-danger btn-sm" onclick="deleteApp('+i+',\''+j.type+'\')"><i class="fas fa-trash"></i> Delete</button>':'<button class="btn btn-success btn-sm" onclick="approveApp('+i+',\''+j.type+'\')"><i class="fas fa-check"></i> Approve</button><button class="btn btn-danger btn-sm" onclick="deleteApp('+i+',\''+j.type+'\')"><i class="fas fa-trash"></i> Delete</button>'}</div>`;return d;}
function approveApp(i,t){const a=JSON.parse(localStorage.getItem('applications')||'[]');a[i].status='approved';localStorage.setItem('applications',JSON.stringify(a));loadDashboard();alert('✅ Approved!');}
function deleteApp(i,t){if(confirm('Delete?')){const a=JSON.parse(localStorage.getItem('applications')||'[]');a.splice(i,1);localStorage.setItem('applications',JSON.stringify(a));loadDashboard();}}
