document.addEventListener('DOMContentLoaded',function(){loadJobs();setupForms();setupNavigation();initRazorpay();});
function setupNavigation(){document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();document.querySelector(a.getAttribute('href')).scrollIntoView({behavior:'smooth',block:'start'});}));}
let razorpayInstance=null;
function initRazorpay(){const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>console.log('Razorpay Ready');document.head.appendChild(s);}
function initiatePayment(amount,type,formData){const o={key:"rzp_test_1DPcnK28sc1T6S",amount:amount*100,currency:"INR",name:"Banti Jobs Portal",description:`${type==='worker'?'Worker Registration':'Job Posting'} Fee`,image:"https://via.placeholder.com/150?text=Banti",handler:r=>{console.log('Payment Success:',r);if(formData){formData.paymentId=r.razorpay_payment_id;formData.status='paid';saveApplication(formData);showSuccess(`✅ Payment Success! ${type==='worker'?'Worker':'Job'} submitted!`);document.getElementById(type==='worker'?'workerForm':'shopkeeperForm').reset();}},prefill:{name:formData.name||formData.ownerName,contact:formData.phone},theme:{color:"#667eea"},modal:{ondismiss:()=>alert('❌ Payment cancelled')}};razorpayInstance=new Razorpay(o);razorpayInstance.open();}
function setupForms(){document.getElementById('payWorkerBtn').addEventListener('click',function(){const d={type:'worker',name:document.getElementById('workerName').value,aadhar:document.getElementById('workerAadhar').value,phone:document.getElementById('workerPhone').value,skills:document.getElementById('workerSkills').value,location:document.getElementById('workerLocation').value,experience:document.getElementById('workerExp').value||0,timestamp:new Date().toISOString()};const f=document.getElementById('workerForm');if(!f.checkValidity()){f.reportValidity();return;}initiatePayment(50,'worker',d);});document.getElementById('payShopkeeperBtn').addEventListener('click',function(){const d={type:'job',shopName:document.getElementById('shopName').value,ownerName:document.getElementById('ownerName').value,location:document.getElementById('shopLocation').value,jobType:document.getElementById('jobType').value,salary:document.getElementById('salary').value,timing:document.getElementById('timing').value,phone:document.getElementById('shopPhone').value,timestamp:new Date().toISOString()};const f=document.getElementById('shopkeeperForm');if(!f.checkValidity()){f.reportValidity();return;}initiatePayment(50,'job',d);});}
function saveApplication(d){let a=JSON.parse(localStorage.getItem('applications')||'[]');a.push(d);localStorage.setItem('applications',JSON.stringify(a));}
function loadJobs(){const a=getApprovedApplications('job'),l=document.getElementById('jobsList');l.innerHTML='';a.forEach(j=>{l.appendChild(createJobCard(j));});}
function getApprovedApplications(t){const a=JSON.parse(localStorage.getItem('applications')||'[]');return a.filter(a=>a.type===t&&a.status==='approved');}
function createJobCard(j){const d=document.createElement('div');d.className='job-card';d.innerHTML=`<h3><i class="fas fa-store"></i> ${j.shopName}</h3><p><strong>Job:</strong> ${j.jobType}</p><p><strong>💰 Salary:</strong> ₹${j.salary}/month</p><p><strong>📍 Location:</strong> ${j.location}</p><p><strong>⏰ Timing:</strong> ${j.timing}</p><p><strong>👤 Owner:</strong> ${j.ownerName}</p><p><strong>📞 Contact:</strong> ${j.phone}</p><div style="margin-top:20px;"><a href="tel:${j.phone}" class="btn btn-primary btn-sm">📱 Call Now</a></div>`;return d;}
function showSuccess(m){const t=document.createElement('div');t.style.cssText='position:fixed;top:100px;right:20px;background:#4caf50;color:white;padding:20px 30px;border-radius:10px;z-index:10000;animation:slideIn 0.3s ease;font-weight:bold;box-shadow:0 10px 30px rgba(0,0,0,0.3);';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),4000);}
